# Generated by Django 6.0.3 on 2026-03-21 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="learner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_learner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="teach_skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skills.userskillteach"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["learner", "status"], name="matching_ma_learner_798e5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["score"], name="matching_ma_score_8af64e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("teacher", "learner", "teach_skill")},
        ),
    ]
