# Generated by Django 6.0.3 on 2026-04-22 14:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_branch_user_college_user_learner_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        help_text="0=Sunday, 1=Monday, … 6=Saturday",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("start_time", models.TimeField(help_text="Start time (HH:MM)")),
                ("end_time", models.TimeField(help_text="End time (HH:MM)")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="online",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "day_of_week"],
                        name="users_avail_user_id_015241_idx",
                    )
                ],
            },
        ),
    ]
