# Generated by Django 6.0.3 on 2026-04-22 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_match", "New Match"),
                            ("session_confirmed", "Session Confirmed"),
                            ("session_reminder", "Session Reminder"),
                            ("session_cancelled", "Session Cancelled"),
                            ("session_completed", "Session Completed"),
                            ("new_message", "New Message"),
                            ("post_reply", "Post Reply"),
                            ("answer_accepted", "Answer Accepted"),
                            ("badge_earned", "Badge Earned"),
                            ("level_up", "Level Up"),
                            ("community_invite", "Community Invite"),
                            ("report_action", "Report Action"),
                            ("system", "System"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=500)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra data (e.g. session_id, match_id, post_id).",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("push", "Push"),
                        ],
                        default="in_app",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_c4d245_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_543da6_idx",
                    ),
                ],
            },
        ),
    ]
