# Generated by Django 6.0.3 on 2026-04-22 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="evidence/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="skills.userskillteach",
                    ),
                ),
            ],
        ),
    ]
