# Generated by Django 6.0.4 on 2026-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_match', 'New Match'), ('session_scheduled', 'Session Scheduled'), ('session_confirmed', 'Session Confirmed'), ('session_reminder', 'Session Reminder'), ('session_cancelled', 'Session Cancelled'), ('session_completed', 'Session Completed'), ('new_message', 'New Message'), ('post_reply', 'Post Reply'), ('answer_accepted', 'Answer Accepted'), ('badge_earned', 'Badge Earned'), ('level_up', 'Level Up'), ('community_invite', 'Community Invite'), ('report_action', 'Report Action'), ('system', 'System')], max_length=30),
        ),
    ]
