# Generated by Django 6.0.3 on 2026-04-22 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(max_length=300)),
                (
                    "icon",
                    models.CharField(
                        default="🏆",
                        help_text="Emoji or icon class name.",
                        max_length=50,
                    ),
                ),
                (
                    "criteria_action",
                    models.CharField(
                        help_text="The action type that counts toward earning this badge.",
                        max_length=50,
                    ),
                ),
                (
                    "criteria_count",
                    models.PositiveIntegerField(
                        help_text="How many times the action must occur."
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="gamification.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
                "unique_together": {("user", "badge")},
            },
        ),
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action that triggered this XP award.", max_length=50
                    ),
                ),
                (
                    "xp_amount",
                    models.IntegerField(
                        help_text="XP awarded (positive) or deducted (negative)."
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Optional FK to the session/post/comment that triggered this.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gamificatio_user_id_4000e4_idx",
                    ),
                    models.Index(
                        fields=["action"], name="gamificatio_action_941c4f_idx"
                    ),
                ],
            },
        ),
    ]
