# Generated by Django 6.0.3 on 2026-03-21 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userskilllearn",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wants_to_learn",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userskillteach",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skills.skill"
            ),
        ),
        migrations.AddField(
            model_name="userskillteach",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userskilllearn",
            unique_together={("user", "skill")},
        ),
        migrations.AlterUniqueTogether(
            name="userskillteach",
            unique_together={("user", "skill")},
        ),
    ]
