# Generated by Django 6.0.3 on 2026-03-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="match",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="matching.match",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatroom",
            ),
        ),
    ]
