# Generated by Django 6.0.4 on 2026-04-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_canonicalize_chatroom_pairs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_chatro_teacher_f37eab_idx',
            old_name='chat_room_pair_idx',
        ),
    ]
